from __future__ import annotations

from typing import Protocol


class Storage(Protocol):
    async def put(self, key: str, data: bytes, content_type: str) -> str: ...
    async def get_bytes(self, key: str) -> bytes: ...
    def public_url(self, key: str) -> str: ...
    async def delete(self, key: str) -> None: ...
